import { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: 'doc',
      label: 'Home',
      id: 'home'
    },
    {
      type: 'doc',
      label: 'Project Overview',
      id: 'project-overview'
    },
    {
      type: 'category',
      label: 'User Stories',
      link: {
        type: 'doc',
        id: 'user-stories', // Acts as the index for this category
      },
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'user-stories', // Automatically includes all files in the user-stories folder
        },
      ],
    },
    {
      type: 'category',
      label: 'Technical Design',
      collapsible: true,
      collapsed: true,
      items: [
        'technical-design/system-architecture',
        'technical-design/api-documentation',
        'technical-design/database-design',
        'technical-design/browser-extension-structure',
      ],
    },
    {
      type: 'category',
      label: 'Design Documentation',
      collapsible: true,
      collapsed: true,
      items: [
        'design-documentation/ui-wireframes',
        'design-documentation/style-guide',
        'design-documentation/ux-research',
      ],
    },
    {
      type: 'doc',
      label: 'Financial Model',
      id: 'financial-model'
    },
    {
      type: 'category',
      label: 'Development',
      collapsible: true,
      collapsed: true,
      items: [
        'development/setup-guide',
        'development/testing',
        'development/ci-cd',
        'development/deployment',
      ],
    },
    {
      type: 'category',
      label: 'FAQ',
      collapsible: true,
      collapsed: true,
      items: [
        'faq/general-faqs',
        'faq/sync-faqs',
      ],
    },
  ],
};

export default sidebars;
